name: tarixiyshaxslar
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  simple_animations: ^5.0.2
  lottie: ^1.1.0
  day_night_switch: ^1.0.4
  flutter_speed_dial: ^7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/


  fonts:
    - family: Rale way-BoldItalic
      fonts:
        - asset: assets/fonts/Raleway-BoldItalic.ttf
          style: italic
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
          weight: 700
